version: 2
updates:
  # Default branch: master
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit version updates to 10 to prevent CI overload
    open-pull-requests-limit: 10
    # Group all version updates (minor and patch)
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    ignore:
    # Major version updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Group all version updates (major, minor and patch)
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
