version: 2
updates:
  # Default branch: master
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit version updates to 10 to prevent CI overload
    open-pull-requests-limit: 10
    ignore:
    # Major version updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
